name: Update Schedule

on:
  workflow_dispatch:

jobs:
  execute-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install requests bs4
        working-directory: ${{ github.workspace }}

      - name: Run Python Script
        run: |
          python scripts/get_schedule.py > data/schedule.json
        working-directory: ${{ github.workspace }}

      - name: Commit and Update Schedule
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/schedule.json
          git commit -m "Update Schedule"
          git push
